version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "SilentGlasses"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    allow:
      - dependency-type: "all"
    reviewers:
      - "SilentGlasses"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
